global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'services'
    scrape_interval: 15s
    static_configs:
      - targets:
          - 'authentication-service:80'
          - 'chatting-service:80'
          - 'notification-service:80'
          - 'userservice:80'
