apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatting-deployment
  labels:
    app: chatting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatting
  template:
    metadata:
      labels:
        app: chatting
    spec:
      containers:
        - name: chatting
          image: chatting-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ConnectionStrings__MongoDb
              value: "mongodb://mongo:27017"
            - name: ConnectionStrings__RabbitMq
              value: "amqp://guest:guest@rabbitmq:5672"
            - name: DatabaseName
              value: "ChatDb"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
