apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatting-deployment
  namespace: chat-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatting
  template:
    metadata:
      labels:
        app: chatting
    spec:
      containers:
      - name: chatting-container
        image: moka12/chatting
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__RabbitMq
          value: "amqp://guest:guest@rabbitmq:5672"
        - name: UserService__Url
          value: "http://userservice:80"
        - name: Authentication__Url
          value: "http://authentication:80"