apiVersion: v1
kind: Service
metadata:
  name: authentication
spec:
  selector:
    app: authentication
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000   # optional: expose externally for frontend
  type: NodePort        # use ClusterIP if you donâ€™t need external access
