name: deploy our microservice app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.AYMAN_DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.AYMAN_DOCKERHUB_USERNAME }} --password-stdin
      - run: docker build -t moka12/authentication ./AuthenticationService
      - run: docker build -t moka12/user ./UserService
      - run: docker build -t moka12/chatting ./ChattingService/ChattingService
      - run: docker build -t moka12/notification ./NotificationService/NotificationService
      - run: docker build -t moka12/frontend ./ChatApp-FE/chime-together-app

    # push code to dockerHub
      - run: docker push moka12/authentication
      - run: docker push moka12/user
      - run: docker push moka12/chatting
      - run: docker push moka12/notification
      - run: docker push moka12/frontend
