name: deploy our microservice app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: docker login - u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t moka12/authentication ./AuthenticationService
      - run: docker build -t moka12/user ./UserService
      - run: docker build -t moka12/chatting ./ChattingService/ChattingService
      - run: docker build -t moka12/notification ./NotificationService/NotificationService

      - run: docker push moka12/authentication
      - run: docker push moka12/user
      - run: docker push moka12/chatting
      - run: docker push moka12/notificationq